-- ========================================
-- 扩展：更多学习资源
-- ========================================
INSERT INTO t_learning_resource (position_code, title, description, resource_type, url, topic, difficulty) VALUES
('JAVA_BACKEND', '深入理解 Java 并发编程', 'AQS 原理与线程池', 'ARTICLE', 'https://javaguide.cn/java/concurrent/', '并发编程', 3),
('JAVA_BACKEND', 'JVM 调优实战指南', 'GC 算法与参数调优', 'ARTICLE', 'https://cloud.tencent.com/developer/article/2560537', 'JVM', 3),
('JAVA_BACKEND', 'Spring Cloud 微服务架构', '服务注册、配置中心、熔断限流', 'ARTICLE', 'http://icyfenix.cn/exploration/projects/microservice_arch_springcloud.html', 'Spring Cloud', 3),
('JAVA_BACKEND', 'MySQL索引优化实战', '索引原理、慢查询优化', 'ARTICLE', 'https://tech.meituan.com/2014/06/30/mysql-index.html', 'MySQL', 2),
('JAVA_BACKEND', 'Redis 深度历险', 'Redis 原理与应用', 'ARTICLE', 'https://pegasuswang.readthedocs.io/zh/latest/database/redis%E6%B7%B1%E5%BA%A6%E5%8E%86%E9%99%A9%E6%A0%B8%E5%BF%83%E5%8E%9F%E7%90%86%E5%92%8C%E5%BA%94%E7%94%A8%E5%AE%9E%E8%B7%B5/book/', 'Redis', 3),
('WEB_FRONTEND', 'Vue 3 组合式 API 最佳实践', 'Composition API 深入', 'ARTICLE', 'https://vuejs.org/guide/extras/composition-api-faq.html', 'Vue3', 2),
('WEB_FRONTEND', 'React Hooks 完全指南', 'useState, useEffect, useCallback 等', 'ARTICLE', 'https://zh-hans.react.dev/reference/react/hooks', 'React', 2),
('WEB_FRONTEND', '前端工程化与构建优化', 'Webpack/Vite、性能优化', 'ARTICLE', 'https://developer.aliyun.com/article/1636709', '工程化', 3),
('WEB_FRONTEND', '深入理解浏览器原理', '渲染流程、事件循环、安全策略', 'ARTICLE', 'https://developer.mozilla.org/zh-CN/docs/Web/Performance/Guides/How_browsers_work', '浏览器原理', 3),
('WEB_FRONTEND', 'CSS 布局技巧大全', 'Flex、Grid、居中方案', 'ARTICLE', 'https://www.ruanyifeng.com/blog/2019/03/grid-layout-tutorial.html', 'CSS', 1),
('PYTHON_ALGO', 'LeetCode 刷题指南', '数据结构与算法经典题目', 'ARTICLE', 'https://github.com/youngyangyang04/leetcode-master', '算法', 2),
('PYTHON_ALGO', '机器学习入门实战', 'Scikit-learn、模型训练、评估', 'ARTICLE', 'https://zhuanlan.zhihu.com/p/592174336', '机器学习', 2),
('PYTHON_ALGO', 'Python 高级特性详解', '装饰器、迭代器、生成器、元编程', 'ARTICLE', 'https://my.oschina.net/emacs_9551789/blog/18778773', 'Python', 2),
('PYTHON_ALGO', '推荐系统入门', '协同过滤、内容推荐、召回排序', 'ARTICLE', 'https://github.com/datawhalechina/fun-rec', '推荐系统', 3),
('PYTHON_ALGO', 'Python 数据结构与算法进阶', '常用算法与LeetCode实战', 'ARTICLE', 'https://datawhalechina.github.io/leetcode-notes/', '算法', 2),
('GAME_CLIENT', 'Unity 官方 Learn 入门路径', 'Unity 编辑器、场景、Prefab、脚本开发', 'COURSE', 'https://learn.unity.com/pathway/junior-programmer', 'Unity基础', 1),
('GAME_CLIENT', 'Unity Essentials', 'Unity官方基础课程', 'COURSE', 'https://learn.unity.com/pathway/unity-essentials', 'Unity基础', 1),
('GAME_CLIENT', 'Unity 游戏开发完整流程', '项目结构、资源管理与发布', 'ARTICLE', 'https://learn.unity.com/pathway/game-development', 'Unity项目', 2),
('GAME_CLIENT', 'Unity ScriptableObject 实战', '数据驱动开发与配置管理', 'ARTICLE', 'https://unity.com/how-to/separate-game-data-logic-scriptable-objects', 'Unity架构', 2),
('GAME_CLIENT', 'Unity Addressables 资源管理', '资源加载与热更新基础', 'ARTICLE', 'https://docs.unity3d.com/Packages/com.unity.addressables@latest', '资源管理', 3),
('GAME_CLIENT', '微软 C# 官方教程', 'C#语言基础与面向对象', 'COURSE', 'https://learn.microsoft.com/en-us/dotnet/csharp/', 'C#', 1),
('GAME_CLIENT', 'C# 集合与泛型', 'List、Dictionary、泛型设计', 'ARTICLE', 'https://learn.microsoft.com/en-us/dotnet/standard/generics/', '数据结构', 2),
('GAME_CLIENT', 'Game Programming Patterns', '游戏开发经典设计模式', 'BOOK', 'https://gameprogrammingpatterns.com/', '设计模式', 2),
('GAME_CLIENT', 'VisuAlgo 数据结构可视化', '数组、链表、树、图算法可视化', 'COURSE', 'https://visualgo.net/en', '算法', 2),
('GAME_CLIENT', 'Unity ScriptableObject 实战', '数据驱动开发与配置管理', 'ARTICLE', 'https://unity.com/how-to/separate-game-data-logic-scriptable-objects', '架构设计', 2),
('GAME_CLIENT', 'Unity Shader Graph 官方教程', '节点式Shader开发', 'COURSE', 'https://learn.unity.com/project/shader-graph', 'Shader', 2),
('GAME_CLIENT', 'Catlike Coding Rendering Tutorials', 'Unity渲染管线与图形学', 'ARTICLE', 'https://catlikecoding.com/unity/tutorials/', '图形学', 3),
('GAME_CLIENT', 'Unity URP 官方文档', 'Universal Render Pipeline 基础', 'ARTICLE', 'https://docs.unity3d.com/Packages/com.unity.render-pipelines.universal@latest', '渲染管线', 3),
('GAME_CLIENT', 'Unity Graphics Programming Book', '图形学与Shader编程实践', 'BOOK', 'https://github.com/IndieVisualLab/UnityGraphicsProgrammingBook1', '图形学', 3),
('GAME_CLIENT', 'Real-Time Rendering 资源索引', '实时渲染学习资料汇总', 'ARTICLE', 'https://www.realtimerendering.com/', '图形学', 3),
('GAME_CLIENT', 'Unity Profiler 官方指南', 'CPU、GPU与内存分析', 'ARTICLE', 'https://docs.unity3d.com/Manual/Profiler.html', '性能优化', 2),
('GAME_CLIENT', 'Unity Mobile Optimization', '移动端性能优化最佳实践', 'ARTICLE', 'https://unity.com/how-to/mobile-game-optimization-tips-part-1', '性能优化', 3),
('GAME_CLIENT', 'Mirror Networking 官方文档', 'Unity多人联机开发', 'ARTICLE', 'https://mirror-networking.gitbook.io/docs/', '网络同步', 3),
('GAME_CLIENT', 'Gaffer On Games Networking', '经典游戏网络同步理论', 'ARTICLE', 'https://gafferongames.com/', '网络同步', 3);
